<a href="https://colab.research.google.com/github/Neelaveninethra/Deep_Learning_laboratory/blob/main/experiment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
##Build a three-layer Artificial Neural Network by implementing the Back propagation algorithm
import numpy as np


In [25]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [34]:
def sigmoid_derivative(x):
  return x*(1-x)

In [27]:
input_size=2
hidden_size=3
output_size=1
learning_rate=0.1

In [28]:
weights_input_hidden = np.random.rand(input_size,hidden_size)
weights_input_hidden

array([[0.0781095 , 0.81799685, 0.52913404],
       [0.48319556, 0.55894234, 0.61480357]])

In [29]:
biases_hidden = np.zeros((1,hidden_size))
biases_hidden

array([[0., 0., 0.]])

In [30]:
weights_hidden_output = np.random.rand(hidden_size,output_size)
weights_hidden_output

array([[0.74855899],
       [0.60961619],
       [0.04147732]])

In [31]:
biases_output = np.zeros((1,output_size))
biases_output

array([[0.]])

In [32]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0],[1],[1],[0]])

In [36]:
epochs=10000
for epoch in range(epochs):
  hidden_layer_input = np.dot(X,weights_input_hidden)+biases_hidden
  hidden_layer_output = sigmoid(hidden_layer_input)
  output_layer_input = np.dot(hidden_layer_output,weights_hidden_output)+biases_output
  predicted_output = sigmoid(output_layer_input)
  loss = 0.5*np.mean((Y-predicted_output)**2)
  output_error = Y-predicted_output
  output_delta = output_error*sigmoid_derivative(predicted_output)
  hidden_layer_error = output_delta.dot(weights_hidden_output.T)
  hidden_layer_delta = hidden_layer_error * sigmoid_derivative(hidden_layer_output)
  weights_hidden_output+= hidden_layer_output.T.dot(output_delta)*learning_rate
  biases_output+=np.sum(output_delta,axis=0,keepdims=True)*learning_rate
  weights_input_hidden+=X.T.dot(hidden_layer_delta)*learning_rate
  biases_hidden += np.sum(hidden_layer_delta, axis=0, keepdims=True) * learning_rate
  if epoch % 1000 == 0:
    print(f"Epoch {epoch}, Loss: {loss}")





Epoch 0, Loss: 0.14460118474780978
Epoch 1000, Loss: 0.12277167171064934
Epoch 2000, Loss: 0.1059087997385616
Epoch 3000, Loss: 0.06863762397699377
Epoch 4000, Loss: 0.01892575106680599
Epoch 5000, Loss: 0.007206967146106769
Epoch 6000, Loss: 0.0040644106365536736
Epoch 7000, Loss: 0.0027461649083545857
Epoch 8000, Loss: 0.002045155178028935
Epoch 9000, Loss: 0.0016169617405139415


In [37]:
test_input = np.array([[0,0],[0,1],[1,0],[1,1]])

In [38]:
hidden_layer_input_test = np.dot(test_input,weights_input_hidden)+biases_hidden


In [40]:
hidden_layer_output_test = sigmoid(hidden_layer_input_test)

In [41]:
output_layer_input_test = np.dot(hidden_layer_output_test,weights_hidden_output)+biases_output

In [42]:
predicted_output_test = sigmoid(output_layer_input_test)

In [43]:
print("\n predicted output after trainingL:")
print(predicted_output_test)


 predicted output after trainingL:
[[0.05379581]
 [0.94951483]
 [0.95117793]
 [0.05310619]]
